### ISSUE TITLE
Cannot compile source code

### ISSUE THREAD

**Issue by Sognus** [adrianchifor/super-hexagon-ai#1]
I tried compile that source on windows and even on linux (centos) with gcc. Both attempts failed with lots of errors. Could you provide some more information about project settings, libs, special settings, etc.? Its not so simple you just could compile it.

**Comment by adrianchifor** [comment]
Its been a long time since I last compiled it but I'm pretty sure I used MinGW. I think on Linux you can do an apt-get for mingw32 and then use g++ as usual.

**Comment by Sognus** [comment]
Did you use some special setup before u was able to compile it? A tried to play with that recently and I was not successfull. Unfortunately I am not experienced with c++ at all, so i cant even guess what i did wrong.
